package br.com.abracowebmanagement.util;

import java.util.TreeMap;

public class PersonUtil {

	
	/**
	 * Create a TreeMap to Populate Country Combo List
	 * @return
	 */
	public TreeMap<String, String> getFullCountryComboList() {
		TreeMap<String, String> countryList = new TreeMap<String, String>();

		countryList.put("Brasil", "Brasil");
		countryList.put("Afeganistão", "Afeganistão");
		countryList.put("África do Sul", "África do Sul");
		countryList.put("Albânia", "Albânia");
		countryList.put("Alemanha", "Alemanha");
		countryList.put("Andorra", "Andorra");
		countryList.put("Angola", "Angola");
		countryList.put("Anguilla", "Anguilla");
		countryList.put("Antilhas Holandesas", "Antilhas Holandesas");
		countryList.put("Antárctida", "Antárctida");
		countryList.put("Antígua e Barbuda", "Antígua e Barbuda");
		countryList.put("Argentina", "Argentina");
		countryList.put("Argélia", "Argélia");
		countryList.put("Armênia", "Armênia");
		countryList.put("Aruba", "Aruba");
		countryList.put("Arábia Saudita", "Arábia Saudita");
		countryList.put("Austrália", "Austrália");
		countryList.put("Áustria", "Áustria");
		countryList.put("Azerbaijão", "Azerbaijão");
		countryList.put("Bahamas", "Bahamas");
		countryList.put("Bahrein", "Bahrein");
		countryList.put("Bangladesh", "Bangladesh");
		countryList.put("Barbados", "Barbados");
		countryList.put("Belize", "Belize");
		countryList.put("Benin", "Benin");
		countryList.put("Bermudas", "Bermudas");
		countryList.put("Bielorrússia", "Bielorrússia");
		countryList.put("Bolívia", "Bolívia");
		countryList.put("Botswana", "Botswana");
		countryList.put("Brunei", "Brunei");
		countryList.put("Bulgária", "Bulgária");
		countryList.put("Burkina Faso", "Burkina Faso");
		countryList.put("Burundi", "Burundi");
		countryList.put("Butão", "Butão");
		countryList.put("Bélgica", "Bélgica");
		countryList.put("Bósnia e Herzegovina", "Bósnia e Herzegovina");
		countryList.put("Cabo Verde", "Cabo Verde");
		countryList.put("Camarões", "Camarões");
		countryList.put("Camboja", "Camboja");
		countryList.put("Canadá", "Canadá");
		countryList.put("Catar", "Catar");
		countryList.put("Cazaquistão", "Cazaquistão");
		countryList.put("Chade", "Chade");
		countryList.put("Chile", "Chile");
		countryList.put("China", "China");
		countryList.put("Chipre", "Chipre");
		countryList.put("Colômbia", "Colômbia");
		countryList.put("Comores", "Comores");
		countryList.put("Coreia do Norte", "Coreia do Norte");
		countryList.put("Coreia do Sul", "Coreia do Sul");
		countryList.put("Costa do Marfim", "Costa do Marfim");
		countryList.put("Costa Rica", "Costa Rica");
		countryList.put("Croácia", "Croácia");
		countryList.put("Cuba", "Cuba");
		countryList.put("Dinamarca", "Dinamarca");
		countryList.put("Djibouti", "Djibouti");
		countryList.put("Dominica", "Dominica");
		countryList.put("Egito", "Egito");
		countryList.put("El Salvador", "El Salvador");
		countryList.put("Emirados Árabes Unidos", "Emirados Árabes Unidos");
		countryList.put("Equador", "Equador");
		countryList.put("Eritreia", "Eritreia");
		countryList.put("Escócia", "Escócia");
		countryList.put("Eslováquia", "Eslováquia");
		countryList.put("Eslovênia", "Eslovênia");
		countryList.put("Espanha", "Espanha");
		countryList.put("Estados Federados da Micronésia", "Estados Federados da Micronésia");
		countryList.put("Estados Unidos", "Estados Unidos");
		countryList.put("Estônia", "Estônia");
		countryList.put("Etiópia", "Etiópia");
		countryList.put("Fiji", "Fiji");
		countryList.put("Filipinas", "Filipinas");
		countryList.put("Finlândia", "Finlândia");
		countryList.put("França", "França");
		countryList.put("Gabão", "Gabão");
		countryList.put("Gana", "Gana");
		countryList.put("Geórgia", "Geórgia");
		countryList.put("Gibraltar", "Gibraltar");
		countryList.put("Granada", "Granada");
		countryList.put("Gronelândia", "Gronelândia");
		countryList.put("Grécia", "Grécia");
		countryList.put("Guadalupe", "Guadalupe");
		countryList.put("Guam", "Guam");
		countryList.put("Guatemala", "Guatemala");
		countryList.put("Guernesei", "Guernesei");
		countryList.put("Guiana", "Guiana");
		countryList.put("Guiana Francesa", "Guiana Francesa");
		countryList.put("Guiné", "Guiné");
		countryList.put("Guiné Equatorial", "Guiné Equatorial");
		countryList.put("Guiné-Bissau", "Guiné-Bissau");
		countryList.put("Gâmbia", "Gâmbia");
		countryList.put("Haiti", "Haiti");
		countryList.put("Honduras", "Honduras");
		countryList.put("Hong Kong", "Hong Kong");
		countryList.put("Hungria", "Hungria");
		countryList.put("Ilha Bouvet", "Ilha Bouvet");
		countryList.put("Ilha de Man", "Ilha de Man");
		countryList.put("Ilha do Natal", "Ilha do Natal");
		countryList.put("Ilha Heard e Ilhas McDonald", "Ilha Heard e Ilhas McDonald");
		countryList.put("Ilha Norfolk", "Ilha Norfolk");
		countryList.put("Ilhas Cayman", "Ilhas Cayman");
		countryList.put("Ilhas Cocos (Keeling)", "Ilhas Cocos (Keeling)");
		countryList.put("Ilhas Cook", "Ilhas Cook");
		countryList.put("Ilhas Feroé", "Ilhas Feroé");
		countryList.put("Ilhas Geórgia do Sul e Sandwich do Sul", "Ilhas Geórgia do Sul e Sandwich do Sul");
		countryList.put("Ilhas Malvinas", "Ilhas Malvinas");
		countryList.put("Ilhas Marshall", "Ilhas Marshall");
		countryList.put("Ilhas Menores Distantes dos Estados Unidos", "Ilhas Menores Distantes dos Estados Unidos");
		countryList.put("Ilhas Salomão", "Ilhas Salomão");
		countryList.put("Ilhas Virgens Americanas", "Ilhas Virgens Americanas");
		countryList.put("Ilhas Virgens Britânicas", "Ilhas Virgens Britânicas");
		countryList.put("Ilhas Åland", "Ilhas Åland");
		countryList.put("Indonésia", "Indonésia");
		countryList.put("Inglaterra", "Inglaterra");
		countryList.put("Índia", "Índia");
		countryList.put("Iraque", "Iraque");
		countryList.put("Irlanda do Norte", "Irlanda do Norte");
		countryList.put("Irlanda", "Irlanda");
		countryList.put("Irã", "Irã");
		countryList.put("Islândia", "Islândia");
		countryList.put("Israel", "Israel");
		countryList.put("Itália", "Itália");
		countryList.put("Iêmen", "Iêmen");
		countryList.put("Jamaica", "Jamaica");
		countryList.put("Japão", "Japão");
		countryList.put("Jersey", "Jersey");
		countryList.put("Jordânia", "Jordânia");
		countryList.put("Kiribati", "Kiribati");
		countryList.put("Kuwait", "Kuwait");
		countryList.put("Laos", "Laos");
		countryList.put("Lesoto", "Lesoto");
		countryList.put("Letônia", "Letônia");
		countryList.put("Libéria", "Libéria");
		countryList.put("Liechtenstein", "Liechtenstein");
		countryList.put("Lituânia", "Lituânia");
		countryList.put("Luxemburgo", "Luxemburgo");
		countryList.put("Líbano", "Líbano");
		countryList.put("Líbia", "Líbia");
		countryList.put("Macau", "Macau");
		countryList.put("Macedônia", "Macedônia");
		countryList.put("Madagáscar", "Madagáscar");
		countryList.put("Malawi", "Malawi");
		countryList.put("Maldivas", "Maldivas");
		countryList.put("Mali", "Mali");
		countryList.put("Malta", "Malta");
		countryList.put("Malásia", "Malásia");
		countryList.put("Marianas Setentrionais", "Marianas Setentrionais");
		countryList.put("Marrocos", "Marrocos");
		countryList.put("Martinica", "Martinica");
		countryList.put("Mauritânia", "Mauritânia");
		countryList.put("Maurícia", "Maurícia");
		countryList.put("Mayotte", "Mayotte");
		countryList.put("Moldávia", "Moldávia");
		countryList.put("Mongólia", "Mongólia");
		countryList.put("Montenegro", "Montenegro");
		countryList.put("Montserrat", "Montserrat");
		countryList.put("Moçambique", "Moçambique");
		countryList.put("Myanmar", "Myanmar");
		countryList.put("México", "México");
		countryList.put("Mônaco", "Mônaco");
		countryList.put("Namíbia", "Namíbia");
		countryList.put("Nauru", "Nauru");
		countryList.put("Nepal", "Nepal");
		countryList.put("Nicarágua", "Nicarágua");
		countryList.put("Nigéria", "Nigéria");
		countryList.put("Niue", "Niue");
		countryList.put("Noruega", "Noruega");
		countryList.put("Nova Caledônia", "Nova Caledônia");
		countryList.put("Nova Zelândia", "Nova Zelândia");
		countryList.put("Níger", "Níger");
		countryList.put("Omã", "Omã");
		countryList.put("Palau", "Palau");
		countryList.put("Palestina", "Palestina");
		countryList.put("Panamá", "Panamá");
		countryList.put("Papua-Nova Guiné", "Papua-Nova Guiné");
		countryList.put("Paquistão", "Paquistão");
		countryList.put("Paraguai", "Paraguai");
		countryList.put("País de Gales", "País de Gales");
		countryList.put("Países Baixos", "Países Baixos");
		countryList.put("Peru", "Peru");
		countryList.put("Pitcairn", "Pitcairn");
		countryList.put("Polinésia Francesa", "Polinésia Francesa");
		countryList.put("Polônia", "Polônia");
		countryList.put("Porto Rico", "Porto Rico");
		countryList.put("Portugal", "Portugal");
		countryList.put("Quirguistão", "Quirguistão");
		countryList.put("Quênia", "Quênia");
		countryList.put("Reino Unido", "Reino Unido");
		countryList.put("República Centro-Africana", "República Centro-Africana");
		countryList.put("República Checa", "República Checa");
		countryList.put("República Democrática do Congo", "República Democrática do Congo");
		countryList.put("República do Congo", "República do Congo");
		countryList.put("República Dominicana", "República Dominicana");
		countryList.put("Reunião", "Reunião");
		countryList.put("Romênia", "Romênia");
		countryList.put("Ruanda", "Ruanda");
		countryList.put("Rússia", "Rússia");
		countryList.put("Saara Ocidental", "Saara Ocidental");
		countryList.put("Saint Martin", "Saint Martin");
		countryList.put("Saint-Barthélemy", "Saint-Barthélemy");
		countryList.put("Saint-Pierre e Miquelon", "Saint-Pierre e Miquelon");
		countryList.put("Samoa Americana", "Samoa Americana");
		countryList.put("Samoa", "Samoa");
		countryList.put("Santa Helena, Ascensão e Tristão da Cunha", "Santa Helena, Ascensão e Tristão da Cunha");
		countryList.put("Santa Lúcia", "Santa Lúcia");
		countryList.put("Senegal", "Senegal");
		countryList.put("Serra Leoa", "Serra Leoa");
		countryList.put("Seychelles", "Seychelles");
		countryList.put("Singapura", "Singapura");
		countryList.put("Somália", "Somália");
		countryList.put("Sri Lanka", "Sri Lanka");
		countryList.put("Suazilândia", "Suazilândia");
		countryList.put("Sudão", "Sudão");
		countryList.put("Suriname", "Suriname");
		countryList.put("Suécia", "Suécia");
		countryList.put("Suíça", "Suíça");
		countryList.put("Svalbard e Jan Mayen", "Svalbard e Jan Mayen");
		countryList.put("São Cristóvão e Nevis", "São Cristóvão e Nevis");
		countryList.put("São Marino", "São Marino");
		countryList.put("São Tomé e Príncipe", "São Tomé e Príncipe");
		countryList.put("São Vicente e Granadinas", "São Vicente e Granadinas");
		countryList.put("Sérvia", "Sérvia");
		countryList.put("Síria", "Síria");
		countryList.put("Tadjiquistão", "Tadjiquistão");
		countryList.put("Tailândia", "Tailândia");
		countryList.put("Taiwan", "Taiwan");
		countryList.put("Tanzânia", "Tanzânia");
		countryList.put("Terras Austrais e Antárticas Francesas", "Terras Austrais e Antárticas Francesas");
		countryList.put("Território Britânico do Oceano Índico", "Território Britânico do Oceano Índico");
		countryList.put("Timor-Leste", "Timor-Leste");
		countryList.put("Togo", "Togo");
		countryList.put("Tonga", "Tonga");
		countryList.put("Toquelau", "Toquelau");
		countryList.put("Trinidad e Tobago", "Trinidad e Tobago");
		countryList.put("Tunísia", "Tunísia");
		countryList.put("Turcas e Caicos", "Turcas e Caicos");
		countryList.put("Turquemenistão", "Turquemenistão");
		countryList.put("Turquia", "Turquia");
		countryList.put("Tuvalu", "Tuvalu");
		countryList.put("Ucrânia", "Ucrânia");
		countryList.put("Uganda", "Uganda");
		countryList.put("Uruguai", "Uruguai");
		countryList.put("Uzbequistão", "Uzbequistão");
		countryList.put("Vanuatu", "Vanuatu");
		countryList.put("Vaticano", "Vaticano");
		countryList.put("Venezuela", "Venezuela");
		countryList.put("Vietname", "Vietname");
		countryList.put("Wallis e Futuna", "Wallis e Futuna");
		countryList.put("Zimbabwe", "Zimbabwe");
		countryList.put("Zâmbia", "Zâmbia");

		return countryList;

	}

}
